apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eyecatcher-def 
  janus-idp.io/tekton: eyecatcher-def
  backstage.io/kubernetes-id: eyecatcher-def
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eyecatcher-def
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml