apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: eyecatcher-def-gitops
  description: This is GitOps manifest for eyecatcher-def   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=eyecatcher-def
    backstage.io/kubernetes-id: eyecatcher-def 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: tnevrlka-rhtap/eyecatcher-def-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:eyecatcher-def
