apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: eyecatcher-def
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eyecatcher-def 
  name: eyecatcher-def
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: eyecatcher-def
    weight: 100 
