apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eyecatcher-def
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eyecatcher-def 
  name: eyecatcher-def
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eyecatcher-def 
